### ISSUE TITLE
Access token only valid for 8 Hours

### ISSUE THREAD

**Issue by joepalexander** [adriankumpf/tesla_auth#11]
Valid for returns 8 hours.
<img width="578" alt="Screenshot 2021-11-25 at 20 35 16" src="https://user-images.githubusercontent.com/43236422/143497749-0f694437-a0e5-4811-b6d3-1d6544e7708f.png">

**Comment by adriankumpf** [comment]
That's how long the tokens are valid. If you want a long-lived Owner API token run `tesla_aurth --owner-api-token`.
