### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by zestysoft** [adriankumpf/tesla_auth#17]
After authenticating with the mfa, the app left me with a white window with "Page Not Found"  -- has Tesla changed something recently?

I got that originally from the mac binary I downloaded and ran (ARM Mac), but it happened even after building the binary myself -- actually when I ran the binary I built, it went straight to that "Page Not Found" screen.

**Comment by adriankumpf** [comment]
What output do you get with `tesla_auth --debug`?
