### ISSUE TITLE
Running on Raspberry Pi

### ISSUE THREAD

**Issue by natrlhy** [adriankumpf/tesla_auth#2]
I pulled down the Linux version and was trying to run it on my Pi (same Pi that is running teslamate).

Are there any dependencies need to run this on Raspbian (buster)?

```
root@teslamate:~# ./tesla_auth -d
-bash: ./tesla_auth: cannot execute binary file: Exec format error
root@teslamate:~# file tesla_auth
tesla_auth: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=615abbf214c7145a0027183d8afcb869dccf209c, for GNU/Linux 3.2.0, stripped
```

**Comment by natrlhy** [comment]
Hm in thinking about this, I'm guessing the captcha requires a UI and human interaction so it would have to run with a desktop enabled or something?

**Comment by adriankumpf** [comment]
Oh the precompiled binaries that are available for download only run on the x86-64 architecture, not on ARM. I'll try to make more architectures available soon.

**Comment by tonybroadbent** [comment]
I just dropped some hints on getting this running on a PI over in the discussion section:
https://github.com/adriankumpf/tesla_auth/discussions/25
