### ISSUE TITLE
Loads infinitely if two MFA devices are added

### ISSUE THREAD

**Issue by Jenjen1324** [adriankumpf/tesla_auth#23]
When two MFA devices are added within the tesla site, the loader is stuck for the 30 seconds and then the login reappears.

As soon as I removed one of the MFA devices, the tesla_auth app seemed to work as expected, asking for the MFA token.

**Comment by adriankumpf** [comment]
What output do you get with `tesla_auth --debug`? I also have two MFA devices linked to my account and do not experience the described behaviour.

**Comment by Jenjen1324** [comment]
Sadly it's not my own car nor my own credentials. I may be able to test it in a week or two again. As this no longer poses an issue for me, I'm fine if you want to close this issue.
