### ISSUE TITLE
tesla_auth: symbol lookup error: tesla_auth: undefined symbol: gdk_display_get_default_seat

### ISSUE THREAD

**Issue by petariga** [adriankumpf/tesla_auth#24]
I downloaded your precompilled binary from Github, Linux OS, Ubuntu, installed all required packages/dependecies. Any idea what is the cause?

**Comment by Jenjen1324** [comment]
Following the function through:
 - http://transit.iut2.upmf-grenoble.fr/doc/libgtk-3-doc/gdk3/GdkDisplay.html
 - https://gtk-rs.org/gtk3-rs/stable/latest/docs/gdk_sys/index.html#
 - https://lib.rs/crates/gdk-sys >> FFI bindings to libgdk-3

Would suggest that `libgdk3.0-cil` is a package you require to run this? Could you try this out?
 - https://packages.ubuntu.com/bionic/cli-mono/libgdk3.0-cil

**Comment by petariga** [comment]
Thank you for your try, I installed "sudo apt install libgdk3.0-cil", however not effect on running the binary, still the same error message.

**Comment by adriankumpf** [comment]
Please try again with the [latest release](https://github.com/adriankumpf/tesla_auth#download) and the required dependencies:

```bash
sudo apt install libwebkit2gtk-4.1-dev
```
