### ISSUE TITLE
Doent works with 2FA

### ISSUE THREAD

**Issue by tydoo** [adriankumpf/tesla_auth#26]
Login : OK
2FA : OK

and after 30s, i have this screen

![image](https://user-images.githubusercontent.com/50534204/150092059-376ee6f8-5f55-4f23-ba21-821dd7688f0e.png)

**Comment by adriankumpf** [comment]
What output do you get with `tesla_auth --debug`? Does it work if you retry a couple times?

**Comment by tydoo** [comment]
```
C:\Users\PTBR06201\Downloads>tesla_auth --debug
DEBUG [tesla_auth] Opening https://auth.tesla.com/oauth2/v3/authorize?response_type=code&client_id=ownerapi&state=QB7NRU_jv3j8JKd_4ATvLA&code_challenge=3NPTYAfBXU7vKOJYDnyiz_Nibtlx_TmQOWacX9D4P0Y&code_challenge_method=S256&redirect_uri=https%3A%2F%2Fauth.tesla.com%2Fvoid%2Fcallback&scope=openid+email+offline_access ...
DEBUG [tesla_auth] URL changed: https://auth.tesla.com/void/callback?code=c40ffbb4a03cb8668ca1dfa75446455a1d2d3d7daf350e47a70b4cfb2ea1&state=QB7NRU_jv3j8JKd_4ATvLA&issuer=https%3A%2F%2Fauth.tesla.com%2Foauth2%2Fv3
DEBUG [reqwest::connect] starting new connection: https://auth.tesla.com/
ERROR [tesla_auth] Request failed
```

**Comment by adriankumpf** [comment]
Can you try to open the logged URLs manually in your browser? A request failure suggests a local problem or that the Tesla servers are not accessible. The latter, however, I can rule out, since it currently works for me.

**Comment by tydoo** [comment]
Yes

I have opened the page ``https://auth.tesla.com/void/callback?code=c40ffbb4a03cb8668ca1dfa75446455a1d2d3d7daf350e47a70b4cfb2ea1&state=QB7NRU_jv3j8JKd_4ATvLA&issuer=https%3A%2F%2Fauth.tesla.com%2Foauth2%2Fv3``

Reponse : 404 not found

**Comment by bt** [comment]
I just tried logging in with my account that has 2FA enabled and it generated the access and refresh tokens successfully.

macOS 12.2, M1 Pro MacBook Pro
