### ISSUE TITLE
Running on Windows 10

### ISSUE THREAD

**Issue by natrlhy** [adriankumpf/tesla_auth#3]
I tried running this on my WIndows 10 PC and get this:

```
C:\Users\myid\Desktop>tesla_auth.exe -d
Error: webview2 error, HRESULT 0x80070002
```

I'll poke around some more as I'm wondeirng if I need to install WebView2. I have a pretty standard install of Windows 10 though and use Firefox as my default browser.

**Comment by adriankumpf** [comment]
As I understood it, WebView2 requires the [preview channel of Microsoft Edge and/or a prerelease version of the WebView2 SDK](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel#downloading-the-prerelease-sdk-and-a-preview-channel). Let me know if you get it working :)

**Comment by natrlhy** [comment]
Not seeing any issues with it after installing the [Canary release of MS Edge](https://www.microsoftedgeinsider.com/en-us/download)!

![image](https://user-images.githubusercontent.com/19696424/133944177-72e22e36-37e8-46a0-a086-884f0c98b1ec.png)

**Comment by adriankumpf** [comment]
Awesome, glad to hear that it works on Windows too. Thanks for the detailed feedback!

**Comment by adriankumpf** [comment]
> Just tried again, this time it shows Generating Token Then error message: An error occured. Please try again ... Server returned error response

We'll need to add extra support for Chinese auth servers. I'll create a separate issue for that.

**Comment by jul2003** [comment]
hi

just install this https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section and it works
no need the canary release of edge
