### ISSUE TITLE
HTTP status client error (401 Unauthorized) for url (https://owner-api.teslamotors.com/oauth/token)

### ISSUE THREAD

**Issue by jaimeagudo** [adriankumpf/tesla_auth#34]
I created 8h tokens just fine, then I stumbled upon this

```bash
./tesla_auth -d --owner-api-token
DEBUG [tesla_auth] Opening https://auth.tesla.com/oauth2/v3/authorize?response_type=code&client_id=ownerapi&state=
XXXXXXXXX&code_challenge_method=S256&redirect_uri=https%3A%2F%2Fauth.tesla.com%2Fvoid%2Fcallback&scope=openid+email+offline_access ...
DEBUG [tesla_auth] URL changed: https://auth.tesla.com/void/callback?code=XXXXXXXXX&state=YYYYYYYY&issuer=https%3A%2F%2Fauth.tesla.com%2Foauth2%2Fv3
DEBUG [reqwest::connect] starting new connection: https://auth.tesla.com/
DEBUG [reqwest::async_impl::client] response '200 OK' for https://auth.tesla.com/oauth2/v3/token
DEBUG [reqwest::connect] starting new connection: https://owner-api.teslamotors.com/
DEBUG [reqwest::async_impl::client] response '401 Unauthorized' for https://owner-api.teslamotors.com/oauth/token
ERROR [tesla_auth] HTTP status client error (401 Unauthorized) for url (https://owner-api.teslamotors.com/oauth/token)

```

I guess it makes no difference but I downloaded latest release (today) and run on Mac with M1 chipset, maybe Tesla changed it's API?

**Comment by jaimeagudo** [comment]
I realised activating MFA the 1 time password or backup code is requested on the UI but still I get 401. 

Any time I run the app the keyboard input is unbearable slow anyway, it takes around 10s to process each character making impossible to type, I always have to paste (same happened with user/password)

**Comment by mherfurt** [comment]
I get the same error. Something must have changed in the process to retrieve a owner-api access key.

**Comment by joepalexander** [comment]
@adriankumpf is any movement being made to rectify this?

**Comment by adriankumpf** [comment]
From what I've read so for, Tesla has dropped support for generating owner API tokens. See for example https://github.com/timdorr/tesla-api/issues/548 So the fix will likely be to remove support from this project as well.

**Comment by joepalexander** [comment]
@adriankumpf So I guess the best we can now hope for is an 8 hour access token?

**Comment by joepalexander** [comment]
Although i guess a way to circumvent this would be to run this headlessly and refresh this on an 7h59m cron job

**Comment by adriankumpf** [comment]
Sure, it depends on your use case. The Owner API tokens also had to be refreshed at some point, right? Just [refresh your access token](https://tesla-api.timdorr.com/api-basics/authentication#refreshing-an-access-token) every couple hours.

**Comment by Tesla0** [comment]
@adriankumpf Just to double-check, does TeslaMate auto-refresh the 8-hour SSO tokens automatically, or would we have to create a cron job ourselves to manually do this or something? Thanks!
