### ISSUE TITLE
Invisible text in entry fields on macOS

### ISSUE THREAD

**Issue by OldManLink** [adriankumpf/tesla_auth#55]
When entering any information on a dialog window (email, password, 2fa code), the typed text is not visible. The app still fetches tokens OK, but it's a weird feeling not seeing what I've typed.

cargo 1.62.0
macOS Big Sur version 11.6.7
MacBook Pro (16-inch, 2019)
Processor 2.3 GHz 8-Core Intel Core i9
Memory 64 GB 2667 MHz DDR4
Graphics AMD Radeon Pro 5500M 4 GB/Intel UHD Graphics 630 1536 MB

**Comment by AgentK20** [comment]
Can confirm, seeing this on MacOS Monterey 12.4 (21F79) with a 2021 M1 Max as well.

**Comment by Cheesebaron** [comment]
It is not visible, but if you switch to another window which accepts input, type a character in that input field, and switch back the text magically appears

**Comment by adriankumpf** [comment]
I'll close this for now, since a new macOS has been released in the meantime and quite a few dependencies have been updated.
