### ISSUE TITLE
Windows 10: WebView2 error. The parameter is incorrect

### ISSUE THREAD

**Issue by Gasur** [adriankumpf/tesla_auth#58]
Running both by double-clicking and in terminal (both CMD and PowerShell) results in an instant crash and the following error message:

`PS C:\Users\Gasur\Downloads\tesla auth> ./tesla_auth.exe`
`Error: WebView2 error: WindowsError(Error { code: 0x80070057, message: The parameter is incorrect. })`

Installation of Edge Canary nor Edge Dev does not work.

**Comment by markusdd** [comment]
same here, does not work in Windows 11

**Comment by ramonsmits** [comment]
Same here with Windows 11. My previous method to obtain a token no longer works:

- https://tesla-info.com/tesla-token.php
- https://github.com/tomhollander/TeslaAuth

So bumped into this but can't test if this application is affected to as it seems the tesla login response has changed for me.

FYI: I'm using 2FA

**Comment by adriankumpf** [comment]
I don't have a Windows machine available myself and can't test it. Do any of the previous [releases](https://github.com/adriankumpf/tesla_auth/releases) work for you? Or does WebView2 perhaps still require a [preview version of Edge](https://www.microsoftedgeinsider.com/en-us/download)?

**Comment by LiBryant** [comment]
I think this tool can only work correctly on a newest OS. I tried Win10, just the same error as Gasur saw, and I tried many versions of Edge or WebView, and none of them worked. Then I tried ubuntu 18.04 on my laptop or the NAS, and both failed to install the lib webkit2gtk-4.1. Finally I installed the latest version of ubuntu 22.04 on my laptop, and the tesla_auth worked correctly this time. It took me 4 days to get it work!

**Comment by MateuszKlatecki** [comment]
I had the same problem on Windows 11 with the 0.6.0 version. I used the older version 0.5.4 and everything worked.

**Comment by adriankumpf** [comment]
> I had the same problem on Windows 11 with the 0.6.0 version. I used the older version 0.5.4 and everything worked.

Interesting. Thanks for testing. Can you try if it works with v0.6.1?

**Comment by ramonsmits** [comment]
> > I had the same problem on Windows 11 with the 0.6.0 version. I used the older version 0.5.4 and everything worked.
> 
> Interesting. Thanks for testing. Can you try if it works with v0.6.1?

I can confirm that 0.6.2 works on Windows 11 22H2 22623.1095 with regular Edge installed.
