### ISSUE TITLE
Cargo Lock file out of date in v0.6.1 release.

### ISSUE THREAD

**Issue by BradenM** [adriankumpf/tesla_auth#59]
Hi,

I've been maintaining an AUR package for tesla_auth @ https://aur.archlinux.org/packages/tesla_auth

While attempting to update it to the latest v0.6.1 release recently tagged, I noticed that the lock file was out of date. Figured I'd let you know!

Thanks.

**Comment by adriankumpf** [comment]
Good catch, thanks! I released v0.6.2 with a synced lock file.
