### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by hugoduraes** [adriankumpf/tesla_auth#63]
I'm getting a segmentation fault error while running tesla_auth on MacOS Ventura running on a 2015 MacbookPro (x86-64).

Any hint on what might be the issue? Is there anything I can provide to help finding the cause?

**Comment by ianmurrays** [comment]
I'm seeing this too. macOS Ventura 13.2.1 (22D68).

**Comment by adriankumpf** [comment]
Seems to be related to the deletion of the browsing data at startup.  Running `tesla_auth --keep-browsing-data`  works for me.
