### ISSUE TITLE
Move to the new teslamate-org organisation?

### ISSUE THREAD

**Issue by fatbasstard** [adriankumpf/tesla_auth#66]
Found out today that there was a new release. I used this repo to authenticate again (I thought that was causing my issues). And when seeing the new organisation being out there, maybe an idea to move this repository to there as well? Since it's sort-of related

**Comment by adriankumpf** [comment]
Since this utility is not strictly related to teslamate, and there are no other contributors besides me, I currently see no reason to move this repo to the organization. Maybe at some other time.
