### ISSUE TITLE
trying to get token: Access denied

### ISSUE THREAD

**Issue by brianmay** [adriankumpf/tesla_auth#67]
Using the client version 0.9.0:

```
Access Denied

You don't have permission to access "http://auth.tesla.com/oauth2/v3/authorize?" on this server.
Reference #18.3f5ad617.1702073152.188d242d
```

This happens before I even enter my email address.

As previously discussed:

* https://github.com/teslamate-org/teslamate/discussions/3554
* https://github.com/timdorr/tesla-api/discussions/328

**Comment by piaolinghjl** [comment]
I have run this service in a docker installed in a ubuntu OS, docker didn't has any error. but I can't see any data when I access it from web-page. there is an alert on the left-top of every items.
error:
An error occurred within the plugin
Object
status:500
statusText:"Internal Server Error"
data:Object
message:"An error occurred within the plugin"
messageId:"plugin.downstreamError"
statusCode:500
traceID:""
config:Object
url:"api/ds/query?ds_type=postgres&requestId=Q115"
method:"POST"
data:Object
requestId:"Q115"
hideFromInspector:false
headers:Object
retry:0
traceId:undefined
message:"An error occurred within the plugin"

**Comment by brianmay** [comment]
Last time I tried this it worked, so will close.
