### ISSUE TITLE
Bearfoos defender alert

### ISSUE THREAD

**Issue by resnostyle** [adriankumpf/tesla_auth#68]
I used the tool and got an alert from Windows Defender about Bearfoos malware running. Is this intended?

**Comment by ramonsmits** [comment]
Can you be more specific? In what file? Unless any nasty things infected after build and that got packaged there could be not reason for it.

**Comment by resnostyle** [comment]
As soon as I completed the login process, the tokens got returned and about a second later I got a pop-up from Windows Defender.
It referenced: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FBearfoos.A!ml&threatid=2147731250

**Comment by resnostyle** [comment]
I went ahead and use it again. Didnt get the alert this time, I assume it's safe enough.
